### ISSUE TITLE
不生成html

### ISSUE THREAD

**Issue by Ryaang** [7Wate/EndOfYear#1]
在github上运行，查看日志能获取RSS地址；
切换到html分支，没有html文件，只有一些css等资源文件

**Comment by 7wate** [comment]
我本地 docker 跑了一下 https://www.zair.top/atom.xml，可以的哈铁铁。 😎😎😎
我看了一下你的主页仓库，config.ini 文件中 web 的值需要配置为 false，而不是 true。
因为 github 的 actions 无法提供 web 服务，所以需要配置为 false 构建静态服务。

**Comment by 7wate** [comment]
rss 源需要设置输出全文，否则数据分析不准确的。

**Comment by Ryaang** [comment]
好的，谢谢，是我不懂规矩，我看web那里填了就跳过了，现在已经成功了
