### ISSUE TITLE
冒昧问一句，这个项目我要怎么使用可以体现它的价值  

### ISSUE THREAD

**Issue by China-Wei** [7Wate/EndOfYear#3]
无意冒犯，我看效果挺好的，但是只看到了几张图片，没太看懂这个项目能给我带来什么便利或者功能

**Comment by 7wate** [comment]
如果最后只看到了几张图片，可能是项目在运行的时候存在错误，可以结合日志排错。

初心是为了给博友们的年终总结，带来一些不一样的快乐。如果喜欢就尝试体验一下，不喜欢就 X 掉 ~

> 世界不是为了你而存在
